### ISSUE TITLE
Duplicates of message for IKEA dimmer node

### ISSUE THREAD

**Issue by LordArchidux** [Dirnei/node-red-contrib-zigbee2mqtt-devices#84] opened 2021-01-20 22:24 UTC
Hej,

pressing the button once results in 3 identical messages from the node (see screenshot).

I'm using version 0.18.1.

Please let me know, if I can provide additional info.

Best regards
LordArchidux

![image](https://user-images.githubusercontent.com/45333063/105248078-187c4d00-5b76-11eb-9f53-e274a7f6701e.png)

**Comment by Andreas-Huber** [comment] 2021-01-21 17:58
Looks like a bug. We have to investigate this further.

**Comment by Dirnei** [comment] 2021-01-22 22:00
@LordArchidux can you describe how I can reproduce this bug? I just tried different deployments but I don't get multiple messages.

**Comment by Andreas-Huber** [comment] 2021-01-26 18:38
I also tried to reproduce it, and I could not manage to get a duplicate message with the dimmers.

These are my results for pressing the button twice, with a few seconds in between the presses.
![image](https://user-images.githubusercontent.com/13376471/105889023-fff4b280-600d-11eb-8bd3-52cc1476c733.png)

**Comment by LordArchidux** [comment] 2021-01-29 14:57
Hej,

thanks for looking into it. My steps were really just adding the block, setting up the bridge config, choosing the dimmer and looking at the output of a single button press.

However, currently I'm not able to choose any devices anymore, but don't have time to look into it right now. Might come back to you in some weeks, when I got more free time for this stuff.

Best regards
LordArchidux

**Comment by Dirnei** [comment] 2021-12-29 22:22
I close the issue for now. I never encountered it on my own. If you (or someone else) encounter the problem again, feel free to open an issue again.

**Closed by Dirnei** 2021-12-29 22:22 UTC
Labels: bug
